[project]
name = "pytorch"
version = "0.1.0"
description = ""
authors = [
    {name = "lucasget",email = "lucasbalves2004@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <3.14 || >3.14.1, <3.15"
dependencies = [
    "torch (>=2.12.0,<3.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "torchvision (>=0.27.0,<0.28.0)",
    "pytorchmetrics (>=0.0.1,<0.0.2)",
    "torchmetrics (>=1.9.0,<2.0.0)"
]

[tool.poetry]
packages = [{include = "pytorch", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
